version: '3.8'

services:
  db: 
    image: postgres:15-alpine
    container_name: gpuflow-db
    restart: always
    environment:
      - POSTGRES_USER=gpuflow
      - POSTGRES_PASSWORD=gpuflow123
      - POSTGRES_DB=gpuflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: gpuflow-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: gpuflow-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # for app connection
      - "15672:15672" # for dashboard 


volumes:
  pgdata: